name: Integration Tests

on:
  push:
#  pull_request:


jobs:
  int-test-npm-audit:
    name: "Integration Test of NPM Audit Report"
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Checkout Sample npm repo
        uses: actions/checkout@v2
        with:
          repository: pmegremis/sample-node-app

      - name: Check pwd for sample node app
        if: always()
        run: pwd

      - name: Run npm audit
        if: always()
        run: |
          npm i
          npm audit --production --json > audit.json

      - name: Run ls command
        if: always()
        run: ls

      - name: Checkout Action Auditor
        if: always()
        uses: actions/checkout@v2

      - name: Run ls command
        if: always()
        run: ls

      - name: Copy npm report to Auditor repo
        if: always()
        run: |
          pwd
          cp home/runner/work/actions-auditor/actions-auditor/audit.json ./actions-auditor/
#
#      - name: Audit checker
#        if: always()
#        id: npm_audit
#        uses: ./actions-auditor/
#        with:
#         REPORT_INPUT: "./actions-auditor/audit.json"
#         AUDIT_TOOL: "npm"
#
#      - name: Integration Test NPM Audit
#        uses: ./actions-nowsecure/.github/actions/schema-validator
#        with:
#          INPUT_DATA: "./actions-auditor/auditors-report.json"

#  int-test-owasp-zap:
#   runs-on: ubuntu-latest
#   env:
#     ID: extra
#   steps:
#     - name: Checkout Actions Auditor
#       uses: actions/checkout@v2
#       with:
#         path: ./actions-auditor/
#
#     - name: Use Node.js 12.x
#       uses: actions/setup-node@v1
#       with:
#         node-version: 12.x
#
#
#     - name: Integration Test Extra Schema
#       uses: ./actions-nowsecure/.github/actions/schema-validator
#       with:
#         MACHINEUSER_GITHUB_TOKEN: ${{ secrets.MACHINEUSER_GITHUB_TOKEN }}
#         INPUT_DATA: ${{ steps.nowsecure_action.outputs.nowsecureReportData }}
